### ISSUE TITLE
understanding "0.95s for fast convergence"

### ISSUE THREAD

**Issue by chenwydj** [zyxxmu/lottery-jackpots#1]
Dear authors,

Thanks for this great work!

I am trying to understand "0.95s for fast convergence" by reading the code. Is this fast convergence achieved by setting masked neurons as 0 during forward and setting as 0.95 during backward?

Thank you very much!

**Comment by zyxxmu** [comment]
Thanks for your interest，

It is right that the masked neurons are set as 0 during forward. However, it is not always 0.95 during backward since the masks might be updated by the STE. For example, it might be 0.98 after several iterations. If possible, please refer to the details of STE or raise more questions here.

**Comment by zyxxmu** [comment]
We recommend you to read the source code at /utils/conv_type.py #L40 to #L65 for better understanding. Thanks.

**Comment by chenwydj** [comment]
I see. Thanks for the explanation!
